using Alissa.Core.Interfaces;

namespace Alissa.Core.Services
{
    /// <summary>
    /// Service for integrating Alissa into external programs and modifying code.
    /// </summary>
    public class CodeIntegrationService : ICodeIntegrationService
    {
        // Constants
        private const string BACKUPS_DIR = "backups";
        private const string CONFIG_DIR = "config";
        private const string MEMORY_DIR = "memory";
        private const string LOGS_DIR = "logs";
        private const string BACKUP_TIMESTAMP_FORMAT = "yyyy-MM-dd_HH-mm-ss";
        private const string BACKUP_EXTENSION = ".bak";
        private const string DEFAULT_LANGUAGE = "csharp";

        private readonly string _basePath;
        private readonly string _backupPath;
        private readonly HashSet<string> _protectedPaths;

        public CodeIntegrationService(string basePath)
        {
            _basePath = basePath;
            _backupPath = Path.Combine(basePath, BACKUPS_DIR);
            _protectedPaths = new HashSet<string>
            {
                Path.Combine(basePath, CONFIG_DIR),
                Path.Combine(basePath, MEMORY_DIR),
                Path.Combine(basePath, LOGS_DIR)
            };

            Directory.CreateDirectory(_backupPath);
        }

        public async Task<string> ReadCodeFileAsync(string filePath)
        {
            bool fileExists = File.Exists(filePath);

            if (fileExists)
            {
                string content = await File.ReadAllTextAsync(filePath);
                return content;
            }

            return string.Empty;
        }

        public async Task<string> AnalyzeCodeAsync(string codeContent, string language = DEFAULT_LANGUAGE)
        {
            // This would integrate with Alissa's analysis capabilities
            // For now, return a placeholder that will be enhanced by the model
            await Task.CompletedTask;

            string result = $"Code analysis for {language}: [analysis would be performed by model]";
            return result;
        }

        public async Task<string> GenerateModificationAsync(string originalCode, string requirement, string language = DEFAULT_LANGUAGE)
        {
            // This would use Alissa's code generation capabilities
            // For now, return a placeholder
            await Task.CompletedTask;

            string result = $"Modified code for {language}: [modifications would be generated by model]";
            return result;
        }

        public async Task WriteModificationAsync(string filePath, string modifiedCode)
        {
            bool isSafe = await IsFileSafeToModifyAsync(filePath);

            if (isSafe)
            {
                await File.WriteAllTextAsync(filePath, modifiedCode);
            }

            await Task.CompletedTask;
        }

        public async Task<bool> IsFileSafeToModifyAsync(string filePath)
        {
            bool isNullOrEmpty = string.IsNullOrWhiteSpace(filePath);

            if (isNullOrEmpty)
            {
                return await Task.FromResult(false);
            }

            bool isProtected = IsPathProtected(filePath);
            bool isSafe = !isProtected;

            return await Task.FromResult(isSafe);
        }

        public bool IsPathProtected(string filePath)
        {
            bool isNullOrEmpty = string.IsNullOrWhiteSpace(filePath);

            if (isNullOrEmpty)
            {
                return true;
            }

            bool isProtected = false;

            for (int i = 0; i < _protectedPaths.Count; i++)
            {
                string protectedPath = _protectedPaths.ElementAt(i);
                bool pathStartsWithProtected = filePath.StartsWith(protectedPath, StringComparison.OrdinalIgnoreCase);

                if (pathStartsWithProtected)
                {
                    isProtected = true;
                    break;
                }
            }

            return isProtected;
        }

        public async Task<string> CreateBackupAsync(string filePath)
        {
            bool fileExists = File.Exists(filePath);

            if (fileExists)
            {
                string fileName = Path.GetFileName(filePath);
                string timestamp = DateTime.Now.ToString(BACKUP_TIMESTAMP_FORMAT);
                string backupPath = Path.Combine(_backupPath, $"{fileName}.{timestamp}{BACKUP_EXTENSION}");

                string originalContent = await File.ReadAllTextAsync(filePath);
                await File.WriteAllTextAsync(backupPath, originalContent);

                return backupPath;
            }

            return string.Empty;
        }
    }
}
