using Alissa.Core.Interfaces;

namespace Alissa.Core.Services
{
    /// <summary>
    /// Service for integrating Alissa into external programs and modifying code.
    /// </summary>
    public class CodeIntegrationService : ICodeIntegrationService
    {
        private readonly string _basePath;
        private readonly string _backupPath;
        private readonly HashSet<string> _protectedPaths;

        public CodeIntegrationService(string basePath)
        {
            _basePath = basePath;
            _backupPath = Path.Combine(basePath, "backups");
            _protectedPaths = new HashSet<string>
            {
                Path.Combine(basePath, "config"),
                Path.Combine(basePath, "memory"),
                Path.Combine(basePath, "logs")
            };

            Directory.CreateDirectory(_backupPath);
        }

        public async Task<string> ReadCodeFileAsync(string filePath)
        {
            bool fileExists = File.Exists(filePath);

            if (fileExists)
            {
                string content = await File.ReadAllTextAsync(filePath);
                return content;
            }
            else
            {
                return string.Empty;
            }
        }

        public async Task<string> AnalyzeCodeAsync(string codeContent, string language = "csharp")
        {
            // This would integrate with Alissa's analysis capabilities
            // For now, return a placeholder that will be enhanced by the model
            await Task.CompletedTask;
            return $"Code analysis for {language}: [analysis would be performed by model]";
        }

        public async Task<string> GenerateModificationAsync(string originalCode, string requirement, string language = "csharp")
        {
            // This would use Alissa's code generation capabilities
            // For now, return a placeholder
            await Task.CompletedTask;
            return $"Modified code for {language}: [modifications would be generated by model]";
        }

        public async Task WriteModificationAsync(string filePath, string modifiedCode)
        {
            bool isSafe = await IsFileSafeToModifyAsync(filePath);

            if (isSafe)
            {
                await File.WriteAllTextAsync(filePath, modifiedCode);
            }

            await Task.CompletedTask;
        }

        public async Task<bool> IsFileSafeToModifyAsync(string filePath)
        {
            bool isNullOrEmpty = string.IsNullOrWhiteSpace(filePath);

            if (isNullOrEmpty)
            {
                return await Task.FromResult(false);
            }

            bool isProtected = false;

            foreach (var protectedPath in _protectedPaths)
            {
                bool pathStartsWithProtected = filePath.StartsWith(protectedPath, StringComparison.OrdinalIgnoreCase);

                if (pathStartsWithProtected)
                {
                    isProtected = true;
                    break;
                }
            }

            bool isSafe = !isProtected;
            return await Task.FromResult(isSafe);
        }

        public async Task<string> CreateBackupAsync(string filePath)
        {
            bool fileExists = File.Exists(filePath);

            if (fileExists)
            {
                string fileName = Path.GetFileName(filePath);
                string timestamp = DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
                string backupPath = Path.Combine(_backupPath, $"{fileName}.{timestamp}.bak");

                await File.WriteAllTextAsync(backupPath, await File.ReadAllTextAsync(filePath));
                return backupPath;
            }
            else
            {
                return string.Empty;
            }
        }
    }
}
